using CleanLogin.Infra.Database.Context;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CleanLogin.Infra.Database
{
    public class CleanLoginContext : CleanLoginAutoGeneratedContext
    {
        public CleanLoginContext()
        {
        }

        public CleanLoginContext(DbContextOptions<CleanLoginAutoGeneratedContext> options) : base(options)
        {
        }
    }
}
